# Generated by Django 3.0.6 on 2020-05-19 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import formulario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Info_Per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=10, unique=True)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellido_P', models.CharField(max_length=50)),
                ('Apellido_M', models.CharField(blank=True, max_length=50, null=True)),
                ('Fecha_nac', models.DateField()),
                ('Domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('Observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['Apellido_P'],
            },
        ),
        migrations.CreateModel(
            name='Modelo_EVALUA_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.IntegerField()),
                ('Año', models.IntegerField()),
                ('Pregunta_1', models.IntegerField()),
                ('Pregunta_2', models.IntegerField()),
                ('Pregunta_3', models.IntegerField()),
                ('Rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.Modelo_Info_Per', to_field='Rut')),
            ],
            options={
                'ordering': ['Año'],
            },
        ),
        migrations.CreateModel(
            name='Modelo_EVALUA_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.IntegerField()),
                ('Año', models.IntegerField()),
                ('Pregunta_1', models.IntegerField()),
                ('Pregunta_2', models.IntegerField()),
                ('Pregunta_3', models.IntegerField()),
                ('Rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.Modelo_Info_Per', to_field='Rut')),
            ],
            options={
                'ordering': ['Año'],
            },
        ),
        migrations.CreateModel(
            name='Modelo_EVALUA_09',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.IntegerField(default=formulario.models.semestre)),
                ('Año', models.IntegerField(default=2020)),
                ('Colegio', models.TextField(default='Colegio Técnico Profesional República Argentina', max_length=150)),
                ('Curso', models.CharField(max_length=3)),
                ('Escolaridad', models.TextField(max_length=250)),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Evaluador', models.TextField(default='Carlos Diego Riquelme González', max_length=100)),
                ('I_ACIERTO', models.IntegerField(default=0)),
                ('I_ERROR', models.IntegerField(default=0)),
                ('I_OMISION', models.IntegerField(default=0)),
                ('IIA1_ACIERTO', models.IntegerField(default=0)),
                ('IIA1_ERROR', models.IntegerField(default=0)),
                ('IIA1_OMISION', models.IntegerField(default=0)),
                ('IIA2_ACIERTO', models.IntegerField(default=0)),
                ('IIA2_ERROR', models.IntegerField(default=0)),
                ('IIA2_OMISION', models.IntegerField(default=0)),
                ('IIA3_ACIERTO', models.IntegerField(default=0)),
                ('IIA3_ERROR', models.IntegerField(default=0)),
                ('IIA3_OMISION', models.IntegerField(default=0)),
                ('IIA4_ACIERTO', models.IntegerField(default=0)),
                ('IIA4_ERROR', models.IntegerField(default=0)),
                ('IIA4_OMISION', models.IntegerField(default=0)),
                ('IIA5_ACIERTO', models.IntegerField(default=0)),
                ('IIA5_ERROR', models.IntegerField(default=0)),
                ('IIA5_OMISION', models.IntegerField(default=0)),
                ('IIA6_ACIERTO', models.IntegerField(default=0)),
                ('IIA6_ERROR', models.IntegerField(default=0)),
                ('IIA6_OMISION', models.IntegerField(default=0)),
                ('IIB1_ACIERTO', models.IntegerField(default=0)),
                ('IIB1_ERROR', models.IntegerField(default=0)),
                ('IIB1_OMISION', models.IntegerField(default=0)),
                ('IIB2_ACIERTO', models.IntegerField(default=0)),
                ('IIB2_ERROR', models.IntegerField(default=0)),
                ('IIB2_OMISION', models.IntegerField(default=0)),
                ('IIB3_ACIERTO', models.IntegerField(default=0)),
                ('IIB3_ERROR', models.IntegerField(default=0)),
                ('IIB3_OMISION', models.IntegerField(default=0)),
                ('IIC1_ACIERTO', models.IntegerField(default=0)),
                ('IIC1_ERROR', models.IntegerField(default=0)),
                ('IIC1_OMISION', models.IntegerField(default=0)),
                ('IIC2_ACIERTO', models.IntegerField(default=0)),
                ('IIC2_ERROR', models.IntegerField(default=0)),
                ('IIC2_OMISION', models.IntegerField(default=0)),
                ('IVA_ACIERTO', models.IntegerField(default=0)),
                ('IVA_ERROR', models.IntegerField(default=0)),
                ('IVA_OMISION', models.IntegerField(default=0)),
                ('IVB_ACIERTO', models.IntegerField(default=0)),
                ('IVB_ERROR', models.IntegerField(default=0)),
                ('IVB_OMISION', models.IntegerField(default=0)),
                ('IVC_ACIERTO', models.IntegerField(default=0)),
                ('IVC_ERROR', models.IntegerField(default=0)),
                ('IVC_OMISION', models.IntegerField(default=0)),
                ('VA_ACIERTO', models.IntegerField(default=0)),
                ('VA_ERROR', models.IntegerField(default=0)),
                ('VA_OMISION', models.IntegerField(default=0)),
                ('V', models.CharField(choices=[('1', 'Composición escrita superior a lo que es propia del nivel escolar.'), ('2', 'Composición escrita presenta pequeños errores, no relevantes al proceso de expresión.'), ('3', 'Composición acorde al nivel escolar.'), ('4', 'Composición inferior a lo esperado acorde al nivel escolar.'), ('5', 'Composición con abundantes errores, no logra expresarse.')], default='1', max_length=1)),
                ('VIA_ACIERTO', models.IntegerField(default=0)),
                ('VIA_ERROR', models.IntegerField(default=0)),
                ('VIA_OMISION', models.IntegerField(default=0)),
                ('VIB_ACIERTO', models.IntegerField(default=0)),
                ('VIB_ERROR', models.IntegerField(default=0)),
                ('VIB_OMISION', models.IntegerField(default=0)),
                ('Rut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formulario.Modelo_Info_Per', to_field='Rut')),
            ],
            options={
                'ordering': ['Año'],
            },
        ),
    ]
